### ISSUE TITLE
Create API to request Skills

### ISSUE THREAD

**Issue by sb-github** [sb-github/extractor#3]
i need an API to request from amount of vacancies by skill

Request
http://domain/folders/?skill=requested_skill
where
**requested_skill** - is **Required**, its a **string**, example of values: _php, adobe, agile, java, soa, etc_

Responce

**in Success:**
the answer is the **LIST**
**[PHP | 15]**
where
php - is a requested skill
15 - is a quantity of open vacancies by requested skill

**in Error:**
ERROR_NO_DATA ; no information in a system

ERROR_COLLECTING_DATA; Collecting started by your request

**Comment by LaYJeL** [comment]
Request

http://192.168.128.245:8081/extractor/crawler/?skill=java

where
java - is Required, its a string, example of values: php, agile, java, mongodb, etc
Type: GET
Response:
In Success:
the answer is the LIST
Example: 
[
    {
        "skill": "java",
        "quantity": 9
    }
]
where
java - is a requested skill
9 - is a quantity of open vacancies by requested skill

in Error:

If you are looking for 
non-existent skill - result will be empty collection:
[ ]
