### ISSUE TITLE
Create API to request Skill with SubSkills

### ISSUE THREAD

**Issue by sb-github** [sb-github/extractor#4]
i need an API to request from amount of vacancies by skill with all sub skills included

Request
http://domain/folders/?skill=requested_skill&subskill=yes
where
requested_skill - is Required, its a string, example of values: php, adobe, agile, java, soa, etc
subskill - is Optional, example of values: yes|no

Responce

in Success:
the answer is the LISTs
[php| 15] ; its a requested skill with quantity of open vacancies on it
[Office | 15] ; its a quantity of related subskills for skill we requested.
[sql | 2]
[js | 2]

**Comment by LaYJeL** [comment]
Request

http://192.168.128.245:8081/extractor/crawler/?skill=java&subskill=yes

where
java - is Required, its a string, example of values: php, agile, java, mongodb, etc
Type: GET
Response:
In Success:
the answer is the LIST
Example:
[
    {
        "skill": "java",
        "quantity": 25
    },
    {
        "skill": "portals",
        "quantity": 2
    },
    {
        "skill": "enterprises",
        "quantity": 2
    },
    {
        "skill": "connected",
        "quantity": 2
    }
]
where
java - is a requested skill
25 - is a quantity of open vacancies by requested skill
Others skills - it's subskills with name and quantity.

**Comment by LaYJeL** [comment]
Request

192.168.128.245:8081/extractor/crawler/?skill=java

where
java - is Required, its a string, example of values: php, agile, java, mongodb, etc
Type: GET
Response:
In Success:
the answer is the LIST
Example:
[
{
"skill": "java",
"quantity": 9
}
]
where
java - is a requested skill
9 - is a quantity of open vacancies by requested skill

in Error:
Result will be empty collection:
[ ]
