### ISSUE TITLE
Create API to run a crawler

### ISSUE THREAD

**Issue by sb-github** [sb-github/extractor#5]
URL: {url}/crawler/run
Type: GET
Check crawler_config file for number of running crawlers. Max number = 4.

 In Success:
response: status 200 ok

In Fail:
response: status "failed", error_description: "text"

**Comment by StasOmelchenko** [comment]
URL: {url}/crawler/run
Type: GET
In Success:
response: status 200 OK
In Fail:
response: status 500 , error_description: "text"

**Comment by StasOmelchenko** [comment]
Request

URL: http://192.168.128.245:8081/extractor/rest/v1/crawler/run?searchcondition=requested_searchcondition
where
requested_searchcondition - is Required, its a string, example of values: php, agile, java, mongodb, etc
Type: GET

Response

In Success:
response: status 200 OK
In Fail:
response: status 500 INTERNAL_SERVER_ERROR, error_description: "text"
