### ISSUE TITLE
Integrate  Graylog into the project.

### ISSUE THREAD

**Issue by LaYJeL** [sb-github/extractor#58]
- [x] Install and configure Elasticsearch

- [x] Install and configure Graylog 

- [x] Manage Logs with Graylog

**Comment by whyatem** [comment]
Access Graylog web interface by visiting this [link](http://192.168.128.245:9000/system/overview).
View java API logs by accessing the [received messages](http://192.168.128.245:9000/search?q=gl2_source_input%3A5a7d900ad601800001d5fd78&relative=0) in dedicated input.
