### ISSUE TITLE
Create Data Base Structure

### ISSUE THREAD

**Issue by sb-github** [sb-github/extractor#8]
Create DB Structure according to the given structure:
![2018-01-10 16 11 41](https://user-images.githubusercontent.com/35269340/34776972-6014cd12-f621-11e7-8f74-3e2ff17bbf44.png)

**Comment by AlexanderTorchynskyi** [comment]
Visit a [ wiki page](https://github.com/sb-github/extractor/wiki/Build-graph-database-structure) to see an example of filling DB with this structure.

**Comment by sb-github** [comment]
Checked.
